{{- if and .Values.enabled .Values.vmagent.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "victoriametrics.vmagent.fullname" . }}
  labels:
    {{- include "victoriametrics.vmagent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "victoriametrics.vmagent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "victoriametrics.vmagent.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
