{{- if and .Values.enabled .Values.vmagent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "victoriametrics.vmagent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "victoriametrics.vmagent.labels" . | nindent 4 }}
{{- end }}
